version: 2.1
jobs:
  build-&-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Install AWS-CLI"
          command: |
            apt update
            apt install -y awscli
      - run:
          name: "ECR Auth"
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR
      - run:
          name: "Build & push"
          command: |
            docker build -t chat-app .
            docker tag chat-app:latest $ECR/chat-app:latest
            docker push $ECR/chat-app:latest
workflows:
  chat-workflow:
    jobs:
      - build-&-push:
          filters:
            branches:
              only:
                - master
