version: 2.1
jobs:
  build-push:
    machine: true
    steps:
      - checkout
      - run:
          name: "Install AWS-CLI"
          command: |
            sudo apt update
            sudo apt install -y awscli
      - run:
          name: "ECR Auth"
          command: |
            eval $(aws ecr get-login --region us-east-1 --no-include-email)
      - run:
          name: "Build & push"
          command: |
            docker build -t chat-app .
            docker tag chat-app:latest $ECR/chat-app:latest
            docker push $ECR/chat-app:latest
workflows:
  chat-workflow:
    jobs:
      - build-push:
          filters:
            branches:
              only:
                - master
